version: '3.8'
services:
  pgdb:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./psql_db/APDB_pollutants.sql:/docker-entrypoint-initdb.d/APDB_pollutants.sql
    ports:
      - 5432:5432
  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    depends_on:
      - pgdb
    volumes:
      - .:/apdb_app
    entrypoint: ["python", "app.py","run"]
    
